//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProductMgmtSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class ProductL
    {
        public int Id { get; set; }
        [Display(Name = "Product Name")]
        [Required(ErrorMessage ="Product Name required!")]
        public string ProductName { get; set; }

        [DisplayName("Category")]
        [Required(ErrorMessage = "Select the Category!")]
        public string Category { get; set; }

        [DisplayName("Price")]
        [Required(ErrorMessage = "Enter the Price!")]
        public string Price { get; set; }

        [DisplayName("Quantity")]
        [Required(ErrorMessage = "Select the Quantity!")]
        public int Quantity { get; set; }

        [DisplayName("Short Description")]
        [Required(ErrorMessage = "Short Description required!")]
        public string ShortDescription { get; set; }

        [DisplayName("Long Description")]
        public string LongDescription { get; set; }

        [DisplayName("Small Image")]
        [Required(ErrorMessage = "Upload Small Image!")]
        public string SmallImage { get; set; }

        [Display(Name = "Large Image")]
        public string LargeImage { get; set; }

        public HttpPostedFileBase SmallImg { get; set; }

        public HttpPostedFileBase LargeImg { get; set; }

    }
}
